#!/usr/bin/env ruby
require "bundler/setup"
Bundler.setup
require "docker"
require "excon"
require "json"

# build token (duh)
BUILD_TOKEN = "E1HZojQmOoQdLu3fUHxQMqLmJnrJjTqm"

# connection header
HEADERS = {
  'Accept'                => 'application/json',
  'Content-Type'          => 'application/json',
  'Accept-Encoding'       => 'gzip',
  'User-Agent'            => "dawn/githook",
  'X-Ruby-Version'        => RUBY_VERSION,
  'X-Ruby-Platform'       => RUBY_PLATFORM
}

REPONAME_REGEX = /(?<username>[a-z][a-z\d-]+)\/(?<repo>[a-z][a-z\d-]+)\.git/

if argv.size < 2
  abort "USAGE: receive <REPONAME> <COMMIT>"
end

argv = ARGV.dup

git_reponame = argv.shift
commit = argv.shift
# reponame validation regex

# validate reponame
if git_reponame.match(REPONAME_REGEX)
  username = $~[:usernane]
  reponame = $~[:repo]
else
  abort "reponame is invalid" unless reponame =~ regex
end

# fetch api_key
connection = Excon.new "http://localhost", headers: HEADERS
api_key = JSON.load(connection.request(
  method: :get,
  expects: 200,
  path: "/api/git/api_key",
  query: {
    username: username,
    build_token: BUILD_TOKEN
  }
).body)["user"]["api_key"]


# do other stuff
