#!/usr/bin/env ruby
require "bundler/setup"
Bundler.setup
require "docker"
require "excon"
require "json"

# build token (duh)
BUILD_TOKEN = "E1HZojQmOoQdLu3fUHxQMqLmJnrJjTqm"

# connection header
HEADERS = {
  'Accept'                => 'application/json',
  'Content-Type'          => 'application/json',
  'Accept-Encoding'       => 'gzip',
  'User-Agent'            => "dawn/githook",
  'X-Ruby-Version'        => RUBY_VERSION,
  'X-Ruby-Platform'       => RUBY_PLATFORM
}

# some variables which need setting
username = "" # TODO
reponame = "" # TODO

# reponame validation regex
regex = /(?<username>[a-z][a-z\d-]+)\/(?<repo>[a-z][a-z\d-]+)\.git/

# validate reponame
abort "reponame is invalid" unless repoanme =~ regex

# fetch api_key
connection = Excon.new "http://localhost", headers: HEADERS
api_key = JSON.load(connection.request(
  method: :get,
  expects: 200,
  path: "/api/git/api_key",
  query: {
    username: username,
    build_token: BUILD_TOKEN
  }
).body)["user"]["api_key"]


# do other stuff
