#!/bin/bash
set -e

export INSTANCE_NAME=`hostname`
export LOGPLEX_CONFIG_REDIS_URL="redis://${REDIS_PORT_6379_TCP_ADDR}:${REDIS_PORT_6379_TCP_PORT}"
export LOGPLEX_SHARD_URLS="redis://${REDIS_PORT_6379_TCP_ADDR}:${REDIS_PORT_6379_TCP_PORT}"
export LOGPLEX_REDGRID_REDIS_URL="redis://${REDIS_PORT_6379_TCP_ADDR}:${REDIS_PORT_6379_TCP_PORT}"
export LOGPLEX_STATS_REDIS_URL="redis://${REDIS_PORT_6379_TCP_ADDR}:${REDIS_PORT_6379_TCP_PORT}"

#export LOGPLEX_CONFIG_REDIS_URL="redis://localhost:6379"
#export LOGPLEX_SHARD_URLS="redis://localhost:6379"
#export LOGPLEX_REDGRID_REDIS_URL="redis://localhost:6379"
#export LOGPLEX_STATS_REDIS_URL="redis://localhost:6379"

export LOCAL_IP="127.0.0.1"
export LOGPLEX_COOKIE="dawnplex"
export LOGPLEX_AUTH_KEY="hd4Dna3UGxqXqtuVkMYF"

cd /opt/logplex
exec bin/logplex