#!/usr/bin/env ruby
require 'net/http'
$stdout.sync = true

while line = STDIN.gets
  old_rev, new_rev, refname = line.split

  if refname == 'refs/heads/master'
    name = Dir.pwd
    name = File.basename(name, File.extname(name))

    http = Net::HTTP.new('localhost', 5000)
    http.read_timeout = 60*5
    http.request_post '/api/git/hook', "name=#{name}" do |response|
      response.read_body do |segment|
        $stdout.write segment
      end
    end

  end
end
