#!/usr/bin/env ruby
require 'net/http'
$stdout.sync = true

while line = STDIN.gets
  old_rev, new_rev, refname = line.split

  if refname == 'refs/heads/master'
    name = Dir.pwd.split("/").last

    http = Net::HTTP.new('localhost', 5000)
    http.request_post '/api/githook', "git=#{name}" do |response|
      response.read_body do |segment|
        $stdout.write segment
      end
    end

  end
end
