#!/bin/sh
sudo apt-get update
sudo apt-get install redis-server mongodb git

sudo apt-get install linux-image-extra-`uname -r`

# Add the Docker repository key to your local keychain
# using apt-key finger you can check the fingerprint matches 36A1 D786 9245 C895 0F96 6E92 D857 6A8B A88D 21E9
sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"

# Add the Docker repository to your apt sources list.
sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"

# update
sudo apt-get update

# install
sudo apt-get install lxc-docker



# install ruby
curl -L https://get.rvm.io | bash

sudo apt-get install libyaml-dev

rvm pkg install openssl
rvm install 2.0.0 \ 
    --with-openssl-dir=$HOME/.rvm/usr \
    --verify-downloads 1
rvm use 2.0.0