#!/usr/bin/env ruby
require "bundler/setup"
Bundler.setup

require 'redis'
require 'yaml'

cfg = YAML.load_file('config/application.yml')

redis_key = "frontend:#{cfg["DAWN_HOST"]}"
redis = Redis.new
redis.rpush(redis_key, "dawn")
redis.rpush(redis_key, "http://172.17.42.1:5000")
# subdomains
redis_key = "frontend:*.#{cfg["DAWN_HOST"]}"
redis.rpush(redis_key, "dawn")
redis.rpush(redis_key, "http://172.17.42.1:5000")