#!/usr/bin/env ruby
require "bundler/setup"
Bundler.setup

require 'redis'
require 'yaml'

cfg = YAML.load_file('config/application.yml')

credentials = {
  pass: cfg["LOGPLEX_PASSWORD"],
  name: cfg["LOGPLEX_USER"],
  channel: "any",
  full_api: "1"
}

redis = Redis.new(host: 'redis-logplex')
redis.mapped_hmset "cred:#{credentials[:name]}", credentials