#!/bin/bash
# provision
# First Password prompt: use the root password here
ansible-playbook provisioning/deploy-root.yml -i provisioning/hosts -k "$@"
# Second Password prompt: use the user password here (user=dawn password=rubyx)
ansible-playbook provisioning/deploy.yml -i provisioning/hosts -k "$@"
