#!/usr/bin/env bash
# Installs docker, curl and git. Clones Dawn to /app.

apt-get update -y
apt get install -y linux-image-extra-`uname -r` curl git
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
echo "deb http://get.docker.io/ubuntu docker main" > /etc/apt/sources.list.d/docker.list
apt-get update -y
apt-get install -y lxc-docker

if [ ! -d /app ]; then
  git clone https://github.com/dawn/dawn /app
fi

docker pull dawn/dawn
docker pull dawn/buildstep
docker pull dawn/logplex
docker pull dawn/gitreceive
